-- MySQL Script generated by MySQL Workbench
-- Sun Dec  6 23:30:48 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yaraneba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yaraneba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yaraneba` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `yaraneba` ;

-- -----------------------------------------------------
-- Table `yaraneba`.`todos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yaraneba`.`todos` (
  `todo_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `todo_title` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '',
  `user_id` INT NOT NULL DEFAULT 0 COMMENT '',
  `description` VARCHAR(2048) NOT NULL DEFAULT '' COMMENT '',
  `deadline` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `progres_status` INT NOT NULL DEFAULT 1 COMMENT '',
  PRIMARY KEY (`todo_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yaraneba`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yaraneba`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_name` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '')
ENGINE = InnoDB;

-- CREATE USER 'scaler' IDENTIFIED BY 'scaler';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
