-- MySQL Script generated by MySQL Workbench
-- Sat Feb 13 14:13:08 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yaraneba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema yaraneba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yaraneba` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `yaraneba` ;

-- -----------------------------------------------------
-- Table `yaraneba`.`todos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yaraneba`.`todos` ;

CREATE TABLE IF NOT EXISTS `yaraneba`.`todos` (
  `todo_id` INT NOT NULL AUTO_INCREMENT,
  `todo_title` VARCHAR(128) NOT NULL DEFAULT '',
  `user_id` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(2048) NOT NULL DEFAULT '',
  `deadline` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `progress_status` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`todo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yaraneba`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yaraneba`.`users` ;

CREATE TABLE IF NOT EXISTS `yaraneba`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(32) NOT NULL DEFAULT '',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

-- SET SQL_MODE = '';
-- GRANT USAGE ON *.* TO root;
-- DROP USER root;
-- SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- CREATE USER 'root' IDENTIFIED BY 'root';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
